# Generated by Django 5.0.4 on 2024-04-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsite',
            name='header_card',
            field=models.ImageField(default='', upload_to='configSite/logo'),
        ),
        migrations.AlterField(
            model_name='configsite',
            name='logo_header',
            field=models.ImageField(default='', upload_to='configSite/logo'),
        ),
    ]
