# Generated by Django 5.0.4 on 2024-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_configsite_header_card_alter_configsite_logo_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsite',
            name='header_card',
            field=models.ImageField(upload_to='configSite/logo'),
        ),
        migrations.AlterField(
            model_name='configsite',
            name='logo_header',
            field=models.ImageField(upload_to='configSite/logo'),
        ),
    ]
