# Generated by Django 5.0.4 on 2024-04-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_configsite_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(default='', max_length=20)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='texto',
        ),
    ]
