# Generated by Django 5.0.4 on 2024-04-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_categoria_alter_configimagesite_options_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
