# Generated by Django 5.0.4 on 2024-04-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
