# Generated by Django 5.0.4 on 2024-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_post_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="titulo",
            field=models.CharField(default="", max_length=80),
        ),
    ]
