# Generated by Django 5.0.4 on 2024-04-22 05:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_post_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="corpo",
            field=tinymce.models.HTMLField(),
        ),
    ]
